---
name: Build Docker Image

on:
  push:
    paths:
      - Dockerfile
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@b9769986761dfcf8828a58eadbd440d1738476f9
        with:
          context: .
          push: false
          tags: latest
